set(sources ${sources}
    src/plugin.cpp
    src/Settings.cpp
    src/hooks/hook.cpp
    src/feed/CompositePairedAnimation.cpp
    src/feed/FeedIconOverlay.cpp
    src/feed/FeedHealthBarOverlay.cpp
    src/feed/FeedPromptSink.cpp
    src/feed/PairedAnimation.cpp
    src/feed/FeedAnimState.cpp
    src/feed/AnimEventSink.cpp
    src/feed/CombatBark.cpp
    src/feed/WitnessDetection.cpp
    src/utils/AnimUtil.cpp
    src/utils/SoundUtil.cpp
    src/integration/OStimIntegration.cpp
    src/integration/PoiseIntegration.cpp
    src/integration/SacrosanctIntegration.cpp
    src/integration/SacrilegeIntegration.cpp
    src/integration/VampireIntegrationUtils.cpp
    src/integration/VampireFeedProxyIntegration.cpp
    src/integration/SkyrimNetIntegration.cpp
    src/utils/MenuCheck.cpp
    src/feed/TargetState.cpp
    src/feed/AnimationRegistry.cpp
    src/integration/UI.cpp
    src/utils/log.cpp
)