set(sources ${sources}
    src/plugin.cpp
    src/Settings.cpp
    src/hooks/hook.cpp
    src/feed/TwoSingleFeed.cpp
    src/feed/FeedIconOverlay.cpp
    src/feed/PairedAnimPromptSink.cpp
    src/feed/CustomFeed.cpp
    src/feed/FeedSession.cpp
    src/feed/WitnessDetection.cpp
    src/utils/AnimUtil.cpp
    src/integration/OStimIntegration.cpp
    src/integration/PoiseIntegration.cpp
    src/integration/SacrosanctIntegration.cpp
    src/integration/SacrilegeIntegration.cpp
    src/integration/VampireIntegrationUtils.cpp
    src/integration/VampireFeedProxyIntegration.cpp
    src/utils/MenuCheck.cpp
    src/feed/TargetState.cpp
    src/feed/AnimationRegistry.cpp
    src/integration/UI.cpp
)